FROM ubuntu:18.04

RUN apt-get update -y
RUN apt-get install -y python3.7 python3-pip

WORKDIR /app

COPY ./requirements.txt /app
RUN pip3 install -r requirements.txt

# ENTRYPOINT [ "python3" ]
# CMD [ "App.py" ]
CMD ["python3", "App.py"]